/**
 * First-time setup wizard for Alan
 * 
 * Runs when ~/.alan/config/agentd.toml doesn't exist
 */

import React, { useState } from 'react';
import { Box, Text, useInput } from 'ink';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { homedir } from 'node:os';

interface InitWizardProps {
  onComplete: () => void;
}

type Provider = 'gemini' | 'openai' | 'anthropic';

export function InitWizard({ onComplete }: InitWizardProps) {
  const [step, setStep] = useState<'welcome' | 'provider' | 'config' | 'done'>('welcome');
  const [selectedProvider, setSelectedProvider] = useState<Provider>('gemini');
  const [config, setConfig] = useState<Record<string, string>>({
    gemini_project_id: '',
    openai_api_key: '',
    anthropic_api_key: '',
  });
  const [cursor, setCursor] = useState(0);

  useInput((input, key) => {
    if (step === 'welcome') {
      if (key.return) {
        setStep('provider');
      }
      return;
    }

    if (step === 'provider') {
      if (key.upArrow) {
        setCursor(c => (c > 0 ? c - 1 : 2));
      } else if (key.downArrow) {
        setCursor(c => (c < 2 ? c + 1 : 0));
      } else if (key.return) {
        const providers: Provider[] = ['gemini', 'openai', 'anthropic'];
        setSelectedProvider(providers[cursor]);
        setStep('config');
      }
      return;
    }

    if (step === 'config') {
      if (key.return) {
        saveConfig();
        setStep('done');
        setTimeout(onComplete, 2000);
      } else if (key.escape) {
        setStep('provider');
      }
      return;
    }
  });

  const saveConfig = () => {
    const configPath = `${homedir()}/.alan/config/agentd.toml`;
    
    let configContent = `# Alan Agent Daemon Configuration
# Generated by alan init wizard

[server]
bind_address = "127.0.0.1:8090"

[llm]
provider = "${selectedProvider}${selectedProvider === 'openai' ? '_compatible' : selectedProvider === 'anthropic' ? '_compatible' : ''}"
`;

    if (selectedProvider === 'gemini') {
      configContent += `
[llm.gemini]
project_id = "${config.gemini_project_id || 'your-project-id'}"
location = "us-central1"
model = "gemini-2.0-flash"
`;
    } else if (selectedProvider === 'openai') {
      configContent += `
[llm.openai]
api_key = "${config.openai_api_key || 'your-api-key'}"
base_url = "https://api.openai.com/v1"
model = "gpt-4o"
`;
    } else if (selectedProvider === 'anthropic') {
      configContent += `
[llm.anthropic]
api_key = "${config.anthropic_api_key || 'your-api-key'}"
base_url = "https://api.anthropic.com/v1"
model = "claude-3-5-sonnet-latest"
`;
    }

    configContent += `
[runtime]
llm_timeout_secs = 180
tool_timeout_secs = 30

[memory]
enabled = true
strict_workspace = true

[defaults]
approval_policy = "on_request"
sandbox_mode = "workspace_write"
`;

    mkdirSync(dirname(configPath), { recursive: true });
    writeFileSync(configPath, configContent);
  };

  if (step === 'welcome') {
    return (
      <Box flexDirection="column" padding={1}>
        <Text bold color="cyan">Welcome to Alan!</Text>
        <Text> </Text>
        <Text>Alan is an AI assistant that runs in your terminal.</Text>
        <Text> </Text>
        <Text>To get started, we need to configure your LLM provider.</Text>
        <Text> </Text>
        <Text color="gray">Press Enter to continue...</Text>
      </Box>
    );
  }

  if (step === 'provider') {
    const providers = [
      { key: 'gemini', name: 'Google Gemini (Vertex AI)', desc: 'Recommended - requires GCP project' },
      { key: 'openai', name: 'OpenAI', desc: 'Requires API key' },
      { key: 'anthropic', name: 'Anthropic Claude', desc: 'Requires API key' },
    ];

    return (
      <Box flexDirection="column" padding={1}>
        <Text bold>Select your LLM provider:</Text>
        <Text> </Text>
        {providers.map((p, i) => (
          <Box key={p.key} flexDirection="column" marginBottom={1}>
            <Text color={cursor === i ? 'green' : 'white'}>
              {cursor === i ? '> ' : '  '}{p.name}
            </Text>
            <Text color="gray">     {p.desc}</Text>
          </Box>
        ))}
        <Text> </Text>
        <Text color="gray">↑↓ to select, Enter to confirm</Text>
      </Box>
    );
  }

  if (step === 'config') {
    return (
      <Box flexDirection="column" padding={1}>
        <Text bold>Configuration</Text>
        <Text> </Text>
        {selectedProvider === 'gemini' && (
          <>
            <Text>Please enter your Google Cloud Project ID:</Text>
            <Text> </Text>
            <Text color="yellow">Note: You'll need to authenticate with gcloud</Text>
            <Text color="yellow">      or set up application default credentials.</Text>
            <Text> </Text>
            <Text color="gray">(Edit ~/.alan/config/agentd.toml later to change)</Text>
          </>
        )}
        {selectedProvider === 'openai' && (
          <>
            <Text>Please enter your OpenAI API Key:</Text>
            <Text> </Text>
            <Text color="yellow">Get your API key from: https://platform.openai.com/api-keys</Text>
            <Text> </Text>
            <Text color="gray">(Edit ~/.alan/config/agentd.toml later to change)</Text>
          </>
        )}
        {selectedProvider === 'anthropic' && (
          <>
            <Text>Please enter your Anthropic API Key:</Text>
            <Text> </Text>
            <Text color="yellow">Get your API key from: https://console.anthropic.com/</Text>
            <Text> </Text>
            <Text color="gray">(Edit ~/.alan/config/agentd.toml later to change)</Text>
          </>
        )}
        <Text> </Text>
        <Text color="gray">Press Enter to create config file, or Esc to go back</Text>
      </Box>
    );
  }

  return (
    <Box flexDirection="column" padding={1}>
      <Text bold color="green">✓ Configuration saved!</Text>
      <Text> </Text>
      <Text>Config file: ~/.alan/config/agentd.toml</Text>
      <Text> </Text>
      <Text>Starting Alan...</Text>
    </Box>
  );
}
